version: '3.8'

volumes:
  db:
  logs:

services:
  node:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
    - postgres
    environment:
      - PORT=${PORT}
      - PGHOST=${PGHOST}
    restart: on-failure
    volumes:
      - logs:/usr/src/app/logs
      - ./src:/usr/src/app/src
    networks:
      - network
  postgres:
    build: './db/'
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESS_DB=${POSTGRESS_DB}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - network
networks:
  network:
    driver: bridge 